name: Run Tests
on:
  pull_request:
    branches:
      - main
jobs:
  test-utils:
    runs-on: ubuntu-latest
    steps:
      - name: Clone and checkout the repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run Utils Tests
        run: npm run test-utils
